name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Welcome Message
          run: echo "first github runner action job"

        - name: List and read file in same step # use pipe | symbol
          run: |
            ls
            cat README.md

        # - name: List files
        #   run: ls

        # - name: Read file
        #   run: cat README.md